USE NIKE


UPDATE MASTER_FILE
SET 
	MASTER_FILE.SEASON= TBL.LAST_SEA,
	MASTER_FILE.[CARRY OVER]=TBL.CO_SEA
FROM 
	(SELECT
		[Prod Cd], 
		case
			WHEN MAX(SEA_INDEX) % 100 = 1 THEN CONCAT('SP',ROUND(MAX(SEA_INDEX)/100,0))
			WHEN MAX(SEA_INDEX) % 100 = 2 THEN CONCAT('SU',ROUND(MAX(SEA_INDEX)/100,0))
			WHEN MAX(SEA_INDEX) % 100 = 3 THEN CONCAT('FA',ROUND(MAX(SEA_INDEX)/100,0))
			ELSE CONCAT('HO',ROUND(MAX(SEA_INDEX)/100,0))
		END AS	LAST_SEA,
		CASE
			WHEN COUNT(DISTINCT SEA_INDEX) >1 THEN 'CARRY OVER'
		ELSE 'SEASONAL'
		END AS CO_SEA
	FROM 
		(SELECT
			CASE
				WHEN LEFT([Cust PO Nbr],2)='SP' THEN CAST(SUBSTRING([Cust PO Nbr],3,2) AS INT)*100+1
				WHEN LEFT([Cust PO Nbr],2)='SU' THEN CAST(SUBSTRING([Cust PO Nbr],3,2) AS INT)*100+2
				WHEN LEFT([Cust PO Nbr],2)='FA' THEN CAST(SUBSTRING([Cust PO Nbr],3,2) AS INT)*100+3
				ELSE CAST(SUBSTRING([Cust PO Nbr],3,2) AS INT)*100+4
			END AS SEA_INDEX,
			LEFT([Cust PO Nbr],4) AS SEA,
			[Prod Cd]
		FROM NEW_SHIPMENT) CTE
	GROUP BY [Prod Cd]) TBL
WHERE
	MASTER_FILE.SKU=TBL.[Prod Cd]