use nike;

SELECT
	S.STORE_CODE, M.DIV, M.GENDER, M.CAT, M.AGE, M.SUB_SILHOUETE,
	CASE
		WHEN SUB_SILHOUETE = 'SOCK' THEN 
			dbo.Maxx(
				ROUND(SUM(QTY_NEED) /COUNT(DISTINCT S.SKU)/6,0)*6,
				12)
		WHEN DIV='FW' THEN 
			dbo.Maxx(
				ROUND(SUM(QTY_NEED) /COUNT(DISTINCT S.SKU)/3,0)*3,9)
		WHEN DIV='AP' THEN dbo.Maxx(ROUND(SUM(QTY_NEED) /COUNT(DISTINCT S.SKU)/3,0)*3,6)
		ELSE dbo.Maxx(ROUND(SUM(QTY_NEED) /COUNT(DISTINCT S.SKU)/3,0)*3,3)
	END AS UPS_STANDARD
FROM 
	-- Group data sales by store_code and sku
	(SELECT
		STORE_CODE, STYLE SKU,
		(SUM(A.QTY) / DATEDIFF(WEEK,MIN(A.CREATED_DATE), MAX(A.CREATED_DATE)) * 13) /0.65 QTY_NEED
	FROM
		SALES_DATA A,
		MASTER_STORE
	WHERE
		STORE_CODE = [STORE CODE] AND
		TIER IN('NSP','DS') AND
		A.VEND_CODE = 'NIKE' AND
		(A.CREATED_DATE BETWEEN '2022-08-01' AND '2023-01-31') AND
		DISC_PERC <30
	GROUP BY STYLE, STORE_CODE
	HAVING DATEDIFF(WEEK,MIN(A.CREATED_DATE), MAX(A.CREATED_DATE)) >0) S

	INNER JOIN
	-- select data from master_file, add in sub_silhouete
	(select *,
	case
		when SILHOUETE LIKE '%SOCK%' THEN 6
		ELSE 3
	END AS DELIVERY,
	CASE
		when DIV='FW' THEN 9
		WHEN DIV='AP' THEN 6
		WHEN SILHOUETE LIKE '%SOCK%' THEN 12
		ELSE 3
	END AS MIN_QTY
	from master_file
	where vend = 'NIKE') M

	--join condition
	ON S.SKU = M.SKU
GROUP BY S.STORE_CODE, M.DIV, M.GENDER, M.CAT, M.AGE, M.SUB_SILHOUETE, DELIVERY, MIN_QTY



